### ISSUE TITLE
Cannot install Massif

### ISSUE THREAD

**Issue by omuyelijah** [FTSRG/massif#22]
Hi,

I am finding difficulty installing Massif core libraries from the update site on my Eclipse environment. It  says that 'Massif Simulink API Feature', 'Massif Simulink EMF Feature' and 'Massif Simulink UI Feature' will not be installed. What could be the problem? I will appreciate insights and assistance.

**Comment by imbur** [comment]
Hi, 
Please make sure you have the appropriate version of EMF-IncQuery (version requirement is [8.0.0,9.0.0), and not the newest available, which is 9.0). Update site: http://eclipse.org/incquery/download.php

**Comment by omuyelijah** [comment]
Thanks. It worked :)
