### ISSUE TITLE
where is MatlabServer.zip?

### ISSUE THREAD

**Issue by amdapi** [FTSRG/massif#32]
Hi,

This is a novice question. I am trying to use the MatlabCommandEvaluation server. In the user guide the following is mentioned "After you downloaded the zip containing the MatlabServer, extract it to a folder on your computer, then make that folder as your current folder in Matlab"

Where is this .zip file located in the repository?

Thanks

**Comment by imbur** [comment]
Hi! 
You can find the link for download in the readme, under Command evaluation server archive. The exact link for the release build ishttp://incquery.net/update/massif/release/

**Comment by amdapi** [comment]
Thanks.
