### ISSUE TITLE
Exception while importing data"hu.bme.mit.massif.communication.datatype.CellMatlabData cannot be cast to hu.bme.mit.massif.communication.datatype.Handle" 

### ISSUE THREAD

**Issue by amdapi** [FTSRG/massif#33]
Hello,

I am a beginner with Massif, Matlab and Eclipse. 

I am  trying to import a simulink model. I have followed the ImporterExample using RMI and implemented an importer example. 

I get an exception at "importer.traverseAndCreateEMFModel(importMode);"

Error while importing data from Matlab/Simulink
Exception Message: hu.bme.mit.massif.communication.datatype.CellMatlabData cannot be cast to hu.bme.mit.massif.communication.datatype.Handle

Any hints would be helpful.

thanks

**Comment by amdapi** [comment]
I get this issue when I use any .slx or .mdl file that I have created. But when I use the sldemo_clutch_import.mdl file from your examples, I do not get this error and the import is successful.

**Comment by abelhegedus** [comment]
Hi,

can you send us an example model where the issue occurs?

Additonally, please tell us the version of Matlab that you are using.

**Comment by amdapi** [comment]
Hi,
Thanks for your reply. There are couple of things I want to clarify

1. I have used both "matlab control" and "command evaluation server" options in eclipse-SimulinkPreferences directly and imported the models that I have created and also your example models. There were no errors for these models for both options.

2. When I have used the importer that I have implemented (nearly the same code that's there in your importer example), using Command Evaluation server, the above error appears, when I use the models that I have created. I get no error when I use your example for this case.

The matlab version I use is R2014b. I am unable to attach a .zip file here. Is there any other way to send these files to you?

**Comment by abelhegedus** [comment]
You can simply send it to abel.hegedus [at] incquerylabs.com.

Additionally, if you can send also the code you are trying to execute, it may help as well.

**Comment by amdapi** [comment]
Hi Again, 

Here is the piece of code that I have used for the importer implementation

			if (connectionEstablished) {
				commandEvaluator = connectionHandler.getCommandEvaluator();
				factory = connectionHandler.getFactory();
				MatlabCommand addModelPath = factory.addPath();

				/* Entire model path with file name and extension */
				matlabFile = sourceFileOption.getFile();

				/*
				 * The path to the Simulink model, end it with a filesystem
				 * separator (the file name is not part of this path)
				 */
				String modelPath2 = matlabFile.getPath();
				int lastBackSlashIndex = modelPath2.lastIndexOf(File.separator);
				modelPath = modelPath2.substring(1, lastBackSlashIndex + 1);

				// The model name should be just the file name without extension
				modelName = matlabFile.getName().replace(".slx", "");
				modelName = matlabFile.getName().replace(".mdl", "");

				addModelPath.addParam(modelPath);
				addModelPath.execute();

				// Model name to save the imported Simulink model library
				String importedModelName = outputPathOption.getValueAsStringValue() +                
File.separator + modelName;
				ModelObject model = new ModelObject(modelName, commandEvaluator);
				model.setLoadPath(modelPath);

				// Get the selected import mode
				ImportMode importMode = resolveSelectedImportMode();
				Importer importer = new Importer(model);
                                //Traverse and save the EMF model
				importer.traverseAndCreateEMFModel(importMode);
				importer.saveEMFModel(importedModelName);
			}

**Comment by abelhegedus** [comment]
Are you running your code as a simple Java application or in Eclipse?

It is possible that there is some extension registration that causes differences in the two cases.

**Comment by amdapi** [comment]
I am running it in Eclipse 

If there were such extension registration differences, would it still work with the example that you have provided and not for the random examples that I have created?

**Comment by abelhegedus** [comment]
That is the strange part:
- it works in our implementation with your models, which would point to some difference in calling the importer
- it works with our models and your implementation, which would point to some difference in the input

I have a feeling that 
1. there is some minor setup that is different in your code than in our UI handler
2. your model has some detail that is not in our example model

You should be able to enable debug mode on the Matlab server side when using the command evaluator (see https://github.com/FTSRG/massif/wiki/UserGuide#command-evaluation-server-matlabserver). You should add [this file](https://github.com/FTSRG/massif/blob/master/tests/br.com.embraer.massif.commandevaluation.tests/testconfig/matlabserverconfig.properties) in the Matlab "current directory (next to setup-remote.m) and uncomment the `debug = true` line. If the configuration is correctly read, you will now see all executed commands on the Matlab console.

This log should prove helpful in determining:
- if there is some difference in the beginning
- list the commands leading to the error

**Comment by abelhegedus** [comment]
Also, can you tell me the full stacktrace for the exception? (or at least the part related to Massif)

**Comment by amdapi** [comment]
Hi, 

The path names were not sent properly to the matlab command. The "debug=true" mode in matlab helped solved the issue.

thanks for your help

**Comment by abelhegedus** [comment]
Great to hear that. You are welcome!

**Comment by abelhegedus** [comment]
Added debug mode documentation to [wiki](https://github.com/FTSRG/massif/wiki/UserGuide#enable-debug-mode)
