### ISSUE TITLE
Build errors setting up oomph development environment

### ISSUE THREAD

**Issue by toeklk** [FTSRG/massif#37]
I was trying to setup a massif development environment using oomph as described at https://github.com/FTSRG/massif/wiki/DevelopersGuide

It seems like everything goes smooth, but I end up with some build errors:
- A missing dependency
```
Bundle 'org.eclipse.incquery.validation.core' cannot be resolved	MANIFEST.MF	/hu.bme.mit.massif.simulink.incquery.validation/META-INF	line 14	Plug-in Problem
```
Yet, AFAICT the org.eclipse.incquery.validation.core plugin is correctly installed in my development environment

- A whole bunch of 
```
EClassTransitiveInstancesKey cannot be resolved to a type	BlockPortsQuerySpecification.java	/hu.bme.mit.massif.simulink.incquery/src-gen/hu/bme/mit/massif/models/simulink/viewer/util	line 106	Java Problem
```
compile errors in the generated code

Development platform is Mars, and I chose the massif master branch

**Comment by toeklk** [comment]
Forgot to add: Development platform is Mars, and I chose the massif master branch

**Comment by abelhegedus** [comment]
Sorry for the late reply.

The following are some steps you can take to solve the issue:
1. Please make sure the Oomph bootstrap tasks have executed successfully (Preferences, Plug-in development, Target platform shows `Modular target` as selected and it contains the proper plugins).
2. Do a full clean of the workspace.
3. Clean and build the `simulink.incquery` project.
4. Open all .eiq files in the `simulink.incquery` project and edit-save each of them to trigger the Eclipse builder of EMF-IncQuery.

If all these did not solve the issue, we will delve further :)

**Comment by toeklk** [comment]
Hi,

On Mon, Nov 2, 2015 at 1:32 PM, Ábel Hegedüs <notifications@github.com>
wrote:

> Sorry for the late reply.
>
> The following are some steps you can take to solve the issue:
> 1. Please make sure the Oomph bootstrap tasks have executed successfully
> (Preferences, Plug-in development, Target platform shows Modular target
> as selected and it contains the proper plugins).
>
Modular target is selected.  It contains incquery (sdk.feature.source,
testing.sdk.feature, viewing.tooling.ui.feature), equinox sdk, eclipse sdk,
xtest sdk, and emf sdk)

> 2. Do a full clean of the workspace.
>
I tried that before, but: no effect.

> 3. Clean and build the simulink.incquery project.
>
No

> 4. Open all .eiq files in the simulink.incquery project and edit-save
> each of them to trigger the Eclipse builder of EMF-IncQuery.
>
No

> If all these did not solve the issue, we will delve further :)
>

Great :-)

**Comment by abelhegedus** [comment]
I have updated the Oomph setup (see fe3229d8), unfortunately I forgot to set the correct Xtext version multiple times in the past.

Thanks for catching this. Can I ask why do you need a Massif development environment instead of installing from an update site (I know it was not available temporarily in the last few days).

**Comment by toeklk** [comment]
On Mon, Nov 2, 2015 at 4:48 PM, Ábel Hegedüs <notifications@github.com>
wrote:

> I have updated the Oomph setup (see fe3229d
> <https://github.com/FTSRG/massif/commit/fe3229d8ada3ad62a71f1da114d7cef87cab2a65>),
> unfortunately I forgot to set the correct Xtext version multiple times in
> the past.
>
I'm not too familiar with oomph.  Does this imply I should restart the
oomph installation, or can I update my existing install?

> Thanks for catching this. Can I ask why do you need a Massif development
> environment instead of installing from an update site (I know it was not
> available temporarily in the last few days).
>
I'm trying to get massif running on a mac OS X machine that has several
versions of Matlab/Simulink installed.  As you saw in issue #36, I first
tried the Command Evaluation based connector, which didn't work out.  The
matlabcontrol based connector seems to work, but its massif
'implementation' uses the latest Matlab/Simulink available on my machine,
and doesn't allow for selecting a particular version of matlab.

So I quickly "hacked" a patch adding a Massif preference for the matlab
control connector.  However, I would like to test it before submitting the
patch :-)

**Comment by abelhegedus** [comment]
> I'm not too familiar with oomph.  Does this imply I should restart the
oomph installation, or can I update my existing install?

Simply pulling the changes and selecting `Help -> Perform setup tasks` should be enough. You only need to select the `Targlet` task, the others did not change.

**Comment by toeklk** [comment]
Thx, that seems to fix the issue! (I did get some build errors in the oslc adaptor plugin, but that's definitely a different error, which I could simply workaround by closing the affected project)
