### ISSUE TITLE
[enhancement] Select matlab version

### ISSUE THREAD

**Issue by toeklk** [FTSRG/massif#38]
Hi,
I've have a first version of a patch that adds a preference for selecting a particular version of MATLAB if multiple versions are installed.

However, when I try to create pull request (using the Github for mac application), I get a permission denied error.

```
You may not have permission to access massif. Check Preferences to make sure you’re still logged in.
```
(I am still logged in)

I'm not too familiar with git and github.  Could you point me what's the best way to submit the patch? TIA

**Comment by imbur** [comment]
Hi!
Couldn't it be the problem, that you did not fork the repository and work in your fork? If yes, then for me what seems to be the simplest way is the following:
0. Export all your changes to a patch file using Eclipse then change to a clean workspace
1. Fork the Massif repository (using the web interface of Github)
2. Clone your fork
3. Apply the patch you created in the 0th step on the projects
4. Git commit, then push
5. Create a pull request (also using the web interface of Github)
Sorry I'm not familiar with Github for mac at all, but the web interface should work this way. Let me know if you need more help!
Cheers

**Comment by abelhegedus** [comment]
First of all, thanks for your plan to contribute!

Also, Marton is right, you need to fork Massif first (https://github.com/FTSRG/massif#fork-destination-box). You don't need to create a patch and the like, just simply add your fork as a remote to your existing repository (https://help.github.com/articles/adding-a-remote/). After that, push your changes to a branch and then create a pull request against the master of this repository.

**Comment by toeklk** [comment]
Thx!  See #39
