### ISSUE TITLE
The support for R2016a

### ISSUE THREAD

**Issue by hongjiawu** [FTSRG/massif#44]
Hello!

When I use the R2014a to import simulink model to eclipse, everything works fine. However, the massif will report cannot find the server for R2016a when importing the simulink model to eclipse. Is that because massif is not supporting R2016a currently?

Thank you very much!

**Comment by abelhegedus** [comment]
Hi,

the Command Evaluation Server connector has a hard-coded map of Matlab versions and Matlab releases here: https://github.com/FTSRG/massif/blob/master/plugins/br.com.embraer.massif.commandevaluation.client/src/br/com/embraer/massif/commandevaluation/client/util/MatlabRunningManager.java#L52

You can try the MatlabControl based connector, and we will also update the map with recent versions.

**Comment by abelhegedus** [comment]
Fixed in Massif 0.5.0
